const proddata = [
  {
    id: 1,
    name: "Chai",
    qt: "10 boxes x 20 bags",
    price: 18,
    stock: 39,
    orders: 0,
  },
  {
    id: 2,
    name: "Chang",
    qt: "24 - 12 oz bottles",
    price: 19,
    stock: 17,
    orders: 40,
  },
  {
    id: 3,
    name: "Aniseed Syrup",
    qt: "12 - 550 ml bottles",
    price: 10,
    stock: 13,
    orders: 70,
  },
  {
    id: 4,
    name: "Chef Anton's Cajun Seasoning",
    qt: "48 - 6 oz jars",
    price: 22,
    stock: 53,
    orders: 0,
  },
  {
    id: 5,
    name: "Chef Anton's Gumbo Mix",
    qt: "36 boxes",
    price: 21.35,
    stock: 0,
    orders: 0,
  },
  {
    id: 6,
    name: "Grandma's Boysenberry Spread",
    qt: "12 - 8 oz jars",
    price: 25,
    stock: 120,
    orders: 0,
  },
  {
    id: 7,
    name: "Uncle Bob's Organic Dried Pears",
    qt: "12 - 1 lb pkgs.",
    price: 30,
    stock: 15,
    orders: 0,
  },
  {
    id: 8,
    name: "Northwoods Cranberry Sauce",
    qt: "12 - 12 oz jars",
    price: 40,
    stock: 6,
    orders: 0,
  },
  {
    id: 9,
    name: "Mishi Kobe Niku",
    qt: "18 - 500 g pkgs.",
    price: 97,
    stock: 29,
    orders: 0,
  },
  {
    id: 10,
    name: "Ikura",
    qt: "12 - 200 ml jars",
    price: 31,
    stock: 31,
    orders: 0,
  },
  {
    id: 11,
    name: "Queso Cabrales",
    qt: "1 kg pkg.",
    price: 21,
    stock: 22,
    orders: 30,
  },
  {
    id: 12,
    name: "Queso Manchego La Pastora",
    qt: "10 - 500 g pkgs.",
    price: 38,
    stock: 86,
    orders: 0,
  },
  {
    id: 13,
    name: "Konbu",
    qt: "2 kg box",
    price: 6,
    stock: 24,
    orders: 0,
  },
  {
    id: 14,
    name: "Tofu",
    qt: "40 - 100 g pkgs.",
    price: 23.25,
    stock: 35,
    orders: 0,
  },
  {
    id: 15,
    name: "Genen Shouyu",
    qt: "24 - 250 ml bottles",
    price: 15.5,
    stock: 39,
    orders: 0,
  },
  {
    id: 16,
    name: "Pavlova",
    qt: "32 - 500 g boxes",
    price: 17.45,
    stock: 29,
    orders: 0,
  },
  {
    id: 17,
    name: "Alice Mutton",
    qt: "20 - 1 kg tins",
    price: 39,
    stock: 0,
    orders: 0,
  },
  {
    id: 18,
    name: "Carnarvon Tigers",
    qt: "16 kg pkg.",
    price: 62.5,
    stock: 42,
    orders: 0,
  },
  {
    id: 19,
    name: "Teatime Chocolate Biscuits",
    qt: "10 boxes x 12 pieces",
    price: 9.2,
    stock: 25,
    orders: 0,
  },
  {
    id: 20,
    name: "Sir Rodney's Marmalade",
    qt: "30 gift boxes",
    price: 81,
    stock: 40,
    orders: 0,
  },
];

const Products: React.FC = () => {
  return (
    <div>
      <h1>Products</h1>
    </div>
  );
};

export default Products;
